[package]
name = "rust8"
version = "0.1.0"
edition = "2021"

[dependencies]
chip8 = { path = "chip8" }
game-loop = { version = "0.9.1", features = ["window"] }
pixels = "0.9.0"
winit = "0.26.0"
winit_input_helper = "0.12.0"
