[package]
name = "rust8"
version = "0.1.0"
authors = ["Mikołaj Rosowski <m.rosowski1@wp.pl>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
fastrand = "1.8.0"
